name: Build

on:
  pull_request: 
    branches:
      - '**' 
  push: 
    branches:
      - master

env:
  PUBLIC_SUPABASE_URL: "dummy_value"
  PUBLIC_SUPABASE_ANON_KEY: "dummy_value"
  PRIVATE_SUPABASE_SERVICE_ROLE: "dummy_value"
  PRIVATE_STRIPE_API_KEY: "dummy_value"
  PUBLIC_SUPABASE_STORAGE_URL: "dummy_value"
  CF_IMAGE_RESIZE_URL: "dummy_value"
  PUBLIC_ENVIRONMENT: "dummy_value"
  RESEND_API_KEY: "dummy_value"
  VITE_PRIVATE_SENTRY_AUTH_TOKEN: "dummy_value"
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: NPM install
        run: npm install

      - name: SvelteKit Build
        run: npm run build
