name: Deploy to Cloudflare

on:
  workflow_run:
    workflows: ["Tests", "Build", "Deploy Migrations to Production", "CI"]
    types:
      - completed

jobs:
  deploy_to_cloudflare:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest

    env:
        DEPLOY_HOOK_PROD: ${{ secrets.DEPLOY_HOOK_PROD }}
        
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to Cloudflare Pages
        run: curl -X POST https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/${{ env.DEPLOY_HOOK_PROD }}
